[project]
name = "snu-downloader"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "MilkClouds", email = "milkclouds@snu.ac.kr" }]
dependencies = [
  "selenium>=4.10.0",
  "python-dotenv>=1.0.0",
  "bs4>=0.0.1",
  "yt-dlp>=2023.7.6",
  "ptest>=2.0.3",
  "seleniumbase>=4.15.15",
  "plyer>=2.1.0",
  "python-telegram-bot==13.15",
  "tqdm>=4.65.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
bypass-selection = true